/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author vifer
 */
public class Ejp39_ImprimirFigura extends javax.swing.JPanel {

    /**
     * Creates new form Ejp39_ImprimirFigura
     */
    public Ejp39_ImprimirFigura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBasefigura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFigura = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPRIMIR FIGURA");
        jLabel1.setOpaque(true);
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INGRESE LA LONGITUD DE LA BASE DE LA FIGURA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 510, 49);

        txtBasefigura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtBasefigura);
        txtBasefigura.setBounds(150, 90, 146, 55);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(339, 90, 130, 55);

        txtFigura.setColumns(20);
        txtFigura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtFigura.setRows(5);
        jScrollPane2.setViewportView(txtFigura);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 190, 430, 270);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int N = Integer.parseInt(txtBasefigura.getText());
            if (N <= 0) {
                JOptionPane.showMessageDialog(null, "¡Error! Ingrese un número positivo");
                return;
            }
            String acumulador = "";
            for (int i = 1; i <= N; i++) {
                for (int e = N; e > i; e--) {
                    acumulador += "  ";
                }
                for (int j = 1; j <= i; j++) {
                    if ((i + j) % 2 == 0) {
                        acumulador += "@ ";
                    } else {
                        acumulador += "# ";
                    }
                }
                acumulador += "\n";
            }
            txtFigura.setText(acumulador);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "¡Error! Ingrese un número entero válido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBasefigura;
    private javax.swing.JTextArea txtFigura;
    // End of variables declaration//GEN-END:variables
}
