package Proyecto;
import javax.swing.JOptionPane;
/**
 *
 * @Jandry Gutierrez
 */
public class Ejp5_CaracteresASCII extends javax.swing.JPanel {
    public Ejp5_CaracteresASCII() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JtInferior = new javax.swing.JTextField();
        JtSuperior = new javax.swing.JTextField();
        JtError = new javax.swing.JTextField();
        btGenerarASCII = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GENERAR CODIGO ASCII ");
        jLabel1.setOpaque(true);
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INFERIOR ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(48, 24, 113, 43);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SUPERIOR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(48, 94, 113, 43);

        JtInferior.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(JtInferior);
        JtInferior.setBounds(167, 30, 210, 37);

        JtSuperior.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JtSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtSuperiorActionPerformed(evt);
            }
        });
        jPanel1.add(JtSuperior);
        JtSuperior.setBounds(167, 97, 210, 43);

        JtError.setEditable(false);
        JtError.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JtError.setFocusable(false);
        JtError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtErrorActionPerformed(evt);
            }
        });
        jPanel1.add(JtError);
        JtError.setBounds(416, 25, 364, 115);

        btGenerarASCII.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btGenerarASCII.setForeground(new java.awt.Color(0, 0, 0));
        btGenerarASCII.setText("GENERAR");
        btGenerarASCII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarASCIIActionPerformed(evt);
            }
        });
        jPanel1.add(btGenerarASCII);
        btGenerarASCII.setBounds(470, 190, 190, 91);

        txaResultado.setEditable(false);
        txaResultado.setColumns(20);
        txaResultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txaResultado.setRows(5);
        txaResultado.setFocusable(false);
        jScrollPane1.setViewportView(txaResultado);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 150, 354, 455);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 310, 190, 93);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void JtSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtSuperiorActionPerformed

    private void JtErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtErrorActionPerformed

    private void btGenerarASCIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarASCIIActionPerformed
        // TODO add your handling code here:
        try {
            int inferior = Integer.parseInt(JtInferior.getText());
            int superior = Integer.parseInt(JtSuperior.getText());
            if (inferior<=0 || superior<=0){
                JtError.setText("Ingrese valores positivos");
                return;
            }
            if (inferior>superior){
                JtError.setText("El numero de inicio no puede ser mayor al final");
                return;
            }
            String resultado = "";
            for (int ascii = inferior; ascii <= superior; ascii++) {
                resultado += ascii + " ='" + (char) ascii + "' "+"\n";
            }
            txaResultado.setText(resultado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese valores numéricos válidos");
        }
    }//GEN-LAST:event_btGenerarASCIIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JtInferior.setText("");
        JtSuperior.setText("");
        JtError.setText("");
        txaResultado.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtError;
    private javax.swing.JTextField JtInferior;
    private javax.swing.JTextField JtSuperior;
    private javax.swing.JButton btGenerarASCII;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResultado;
    // End of variables declaration//GEN-END:variables
}
